apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-init-script
  namespace: redis
data:
  sentinel_init.sh: |
    #!/bin/bash

    for i in ${REDIS_NODES//,/ }
    do
        echo "finding master at $i"
        MASTER=$(redis-cli --raw -h $i -a ${REDIS_PASSWORD} info replication | awk '{print $1}' | grep master_host: | cut -d ":" -f2)
    
        if [ "${MASTER}" == "" ]; then
            echo "no master found"
            MASTER=
        else
            echo "found ${MASTER}"
            break
        fi
    
    done

    echo "sentinel monitor mymaster ${MASTER} 6379 2" >> /tmp/master
    echo "port 26379
    $(cat /tmp/master)
    sentinel down-after-milliseconds mymaster 1000
    sentinel failover-timeout mymaster 10000
    sentinel parallel-syncs mymaster 1
    sentinel config-epoch mymaster 255
    sentinel leader-epoch mymaster 255
    maxclients 10000
    dir "/data"
    sentinel auth-pass mymaster ${REDIS_PASSWORD}

    " > /etc/redis/sentinel.conf
    cat /etc/redis/sentinel.conf