apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: redis
  labels:
    app: redis-sentinel
    app.kubernetes.io/component: redis-sentinel
    app.kubernetes.io/instance: redis-sentinel
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: 26379
      targetPort: 26379
      name: sentinel
  selector:
    app: redis-sentinel